apiVersion: v1
kind: Service
metadata:
  name: promptly
  labels:
    app: promptly
    app.kubernetes.io/name: promptly
    app.kubernetes.io/component: server
spec:
  selector:
    app: promptly
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
